### ISSUE TITLE
Add a separate JS file for quiz questions

### ISSUE THREAD

**Issue by barty-s** [KTC96/Didyouhearthat#10]
### Story

As a *developer**, I can **add a JS file** so that I can **link it to the script.js**.

### Acceptance Criteria

- Name the file questions.js or something similar
- Import the file in script.js

### Tasks

- [ ] Added file to the repo
- [ ] Chose a suitable name for the file
- [ ] Linked the file to the script.js file

**Comment by URiem** [comment]
I have added a questions.js file on my local repo and am happy to merge that with the original repo later.
