### ISSUE TITLE
User story -  accessibility 

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#100]
### Story

As a **player**, I can **use screen readers** so that I can **play despite my disability**.

### Acceptance Criteria

- All links etc have aria-labelling
- As many as practical of the accessibility issues are addressed.

### Tasks

- [ ] Put the site through light house and or other accessibility validators
- [ ] check each page for aria-labels
- [ ] Complete any additional accessibility / screen reader requirements
