### ISSUE TITLE
User story - Welcome screen

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#14]
### Story

As a **player**, I can **start playing for the first time** so that I can **become familiar with the game**.

### Acceptance Criteria

- Welcome screen that is just for first launch of the game not if you wish to repeat play
- Request a user's name and have a place that it is obvious they should put their name
- An obvious way for the user to access the instructions if clicked

### Tasks

- [ ] Build welcome screen layout
- [ ] Provide a space to input user name - storage and use of user name in separate user story
- [ ] Provide button/link to a set of instructions and connect to instructions

**Comment by RachWalm** [comment]
Decided to have the instructions on the welcome page and that a link to a reminder of the instructions would become a could have see issue 17 and 52
