### ISSUE TITLE
User story - game starts

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#16]
### Story

As a **player**, I can **move on from welcome page** so that I can **play the game**.

### Acceptance Criteria

- Welcome page is no longer visible once options/name has been completed on welcome page and submitted
- Main layout for game play is now in action

### Tasks

- [x] Once user name (and anything else on Welcome page) is complete moves to main part of the game
- [x] Screen changed to setup for game play
- [x] All Welcome page functionality that is no longer required is removed/hidden
