### ISSUE TITLE
User story - getting to instructions

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#17]
### Story

As a **player**, I can **click instructions/nav button** so that I can **go to instructions**.

### Acceptance Criteria

- When clicking instructions nav/button it takes you to the instructions
- This also occurs once the code has been deployed

### Tasks

- [ ] Connect instructions nav/button to instructions
- [ ] Check that it works
- [ ] Wait for it to go to deployed version and check that it works on deployed version
