### ISSUE TITLE
User story - game HTML layout

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#18]
### Story

As a **player**, I can **look at the screen** so that I can **see all the information I need to play**.

### Acceptance Criteria

- It must be clear what each section of the screen imparts to the user
- All below functions (that we decide to put in place) must have HTML set up - don't need to function just be available to functionality

### Tasks

- [x] Any text that is needed to instruct player
- [x] Area for sound effect to be played visual
- [x] Replay sound button
- [x] Instruction to pick an option
- [x] Radial button options with id's for the options to be put in
- [x] If we are going to allow them to change mind a submit button
- [x] Ongoing score display area
