### ISSUE TITLE
User story - Design Mockup

### ISSUE THREAD

**Issue by KTC96** [KTC96/Didyouhearthat#2]
### Story

As a **developer**, I can **create a design mockup** so that I can **easily see how to design and style my website**.

### Acceptance Criteria

- Design that is easy to understand and follow
- Nice UX and UI elements which capture the interest of the player
- Colour scheme which allows suitable contrast

### Tasks

- [ ] Create a mockup for mobile
- [ ] Share to the group
- [ ] This is one of the tasks that needs to be done
