### ISSUE TITLE
User Story -  Replay sound

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#21]
### Story

As a **player**, I can **click replay** so that I can **listen to sound again**.

### Acceptance Criteria

- Function plays correct sound when the button for replay is pressed
- Adding this function hasn't broken the auto-play feature and they play the same sound
- When deployed still meets above requirements

### Tasks

- [x] Build function to replay the sound
- [x] Connect the button on the quiz page to the replay sound function
- [x] Check it plays automatically when the question is loaded and when replay button is clicked

**Comment by KTC96** [comment]
Sound does not play automatically, but not sure it needs to
