### ISSUE TITLE
User Story - Score

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#24]
### Story

As a **developer**, I can **retain and update a score** so that I can **keep an accurate score**.

### Acceptance Criteria

- Score must not carry over if you are replaying
- function accurately increments score if the player got the question correct
- Score is always correct at every stage of the game
### Tasks

- [ ] Start score at zero
- [ ] Create function that takes retained score and increments it or not depending on whether comparison of answers function is true
- [ ] Provides a score that can be displayed on each question and at the end
