### ISSUE TITLE
User Story - Final Score page HTML

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#27]
### Story

As a **player**, I can **see my end score** so that I can **know my score at the end of the game**.

### Acceptance Criteria

- Clear that the game is over
- Clear final score
- Button to play again without going through welcome screen/reenter name etc. explained and present - functionality on another issue
- Button to instructions

### Tasks

- [ ] HTML layout of page
- [ ] Text congratulating the player and explaining they have answered a full set of questions so the game is over
- [ ] A final score
- [ ] Button to go back game not through welcome screen 
- [ ] Button to re-read the instructions incase they have played but didn't get it

**Comment by RachWalm** [comment]
probably not implement separate instructions
