### ISSUE TITLE
User Story - Finished game but want to redo

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#29]
### Story

As a **player**, I can **play again** so that I can **improve my score**.

### Acceptance Criteria

- All information part of previous game has been removed
- New game starts

### Tasks

- [ ] Build a function that clears out the score and results and anything else from last game
- [ ] Function takes you back to the beginning so that you can play again, but not back to Welcome page as you don't need to do that again
- [ ] Connect function to the play again button on the finish page
