### ISSUE TITLE
User story - File structure

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#3]
### Story

As a **developer**, I can **find required files** so that I can **use the file structure and backbone of documents**.

### Acceptance Criteria

- Set in a conventional file structure 
- Backbone of files with boiler plate code in place
- Available on main

### Tasks

- [x] build file structure
- [x]  add boiler plate code
- [x]  push to main as a learning experience for all on slack call
