### ISSUE TITLE
User story - Instruction text created

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#5]
### Story

As a **player**, I can **read the instruction text** so that I can **understand how to play the game**.

### Acceptance Criteria

- Explains objective of the game
- Tells player how to move through the game
- Describes activities that have any restrictions i.e. name required text
- Easy to read format

### Tasks

- [x] Write a clear concise objective
- [x] Write instructions on using the functions
- [x] State any restrictions that the functionality imposes
