### ISSUE TITLE
User Story - Nav bar

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#50]
### Story

As a **player**, I can **click the nav bar** so that I can **go to instructions or details of devlopers**.

### Acceptance Criteria

- Good looking Nav bar on each page
- Correctly links to the correct place
- Once deploys still links to correct place

### Tasks

- [ ] Create a Nav bar and put it on each page that links to instructions and developers details to open in new tab
- [ ] Style or raise a new issue for the nav bar to be styled
- [ ] Connect relevant links
