### ISSUE TITLE
User story README.md (except testing)

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#54]
### Story

As a **developer**, I can **read the readme** so that I can **understand the game**.

### Acceptance Criteria

- All sections complete below
- Relevant contributors checked their sections.
- This is an example of something that must be achieved for the story to be considered complete

### Tasks

- [ ] Complete Features section
- [ ] Complete Typography and color scheme section
- [ ] Add wireframes
- [ ] Add any additional technology used
- [ ] Add deployment
- [ ] Get people to check their sections
