### ISSUE TITLE
User story - Sound content finding

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#7]
### Story

As a **developer**, I can **have some content sounds** so that I can **add them to the quiz**.

### Acceptance Criteria

- Sounds must be in a suitable format for use
- Sounds must be scary or halloween/horror ish

### Tasks

- [x] Look into how horror sound effects are produced
- [x] Find some open source content of these sounds in appropriate format to be used on the quiz
- [x] Get a collection of these sounds shared with the group
