### ISSUE TITLE
User Story - Create HTML structure/pages - instructions, game & scores

### ISSUE THREAD

**Issue by URiem** [KTC96/Didyouhearthat#8]
### Story

As a **player**, I can **access different pages/functionalities** so that I can **engage with certain tasks: read instructions, play the game, and check my score.**.

### Acceptance Criteria

- Instructions are displayed on a page.
- Game displays and can be played on a separate page.
- High scores are displayed on a separate page.

### Tasks

- [x] Implement a page that shows instructions.
- [x] Implement a page for playing the game.
- [x] Implement a page to save/display high scores.

**Comment by KTC96** [comment]
This wont be finished today
