### ISSUE TITLE
User Story - End of game page displays result and gives option to play again

### ISSUE THREAD

**Issue by URiem** [KTC96/Didyouhearthat#85]
### Story

As a **player**, I can **see my score at the end of the game and am given a choice to play again** so that I can **repeat the game**.

### Acceptance Criteria

- Final score displays on end game page
- Buttons function to play the game again
- Option to save the score is given.

### Tasks

- [x] Display final score
- [x] Functioning buttons to replay the game
- [x] Button to save the score
