### ISSUE TITLE
User Story -  Presentation

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#90]
### Story

As a **Judge**, I can **watch the presentation** so that I can **decide who wins the hackathon**.

### Acceptance Criteria

- Suitable content for the video collected and agreed with team
- Video recorded
- Video shared with team

### Tasks

- [ ] Decide content of the presentation and agree with team
- [ ] Put content together ready to make the video
- [ ] Make the video
- [ ] Share with team
