### ISSUE TITLE
User Story - Questions split into categories

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#92]
### Story

As a **player**, I can **play a different round/level** so that I can **maintain interest**.

### Acceptance Criteria

- Questions split into categories and load correctly on local and deployed version.

### Tasks

- [x] Decide on categories
- [x] Choose which go to each category
- [x] Split the store of questions
